export const elements = {
  searchBar: document.getElementById("searchbar"),
  searchButton: document.getElementById("searchButton"),
  popularContainer: document.getElementById("popular"),
  nowPlayingContainer: document.getElementById("nowPlaying"),
  actionContainer: document.getElementById("action"),
  dramaContainer: document.getElementById("drama"),
  comedyContainer: document.getElementById("comedy"),
  sciFiContainer: document.getElementById("sciFi"),
  horrorContainer: document.getElementById("horror"),
  backdropContainer: document.querySelector(".backdrop-container"),
  filmInfoContainer: document.querySelector(".info-container"),
  filmTitle: document.getElementById("film-title"),
  filmYear: document.getElementById("film-year"),
  filmRating: document.getElementById("film-rating"),
  filmGenres: document.getElementById("film-genres"),
  descriptionContainer: document.querySelector(".film-description-container"),
  filmDescription: document.getElementById("film-description"),
  filmCastList: document.getElementById("film-cast-list"),
  recommendedContainer: document.getElementById("recommended"),
};
